AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  XeexExcDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/XeexExcData
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        XeexExcInsert:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api
            Method: post
        XeexExcQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api
            Method: get
  XeexExcSoftwareFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/XeexExcSoftware
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        XeexExcInsert:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api-sw
            Method: post
        XeexExcQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api-sw
            Method: get
  XeexExcMappingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/XeexExcMapping
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        XeexExcInsert:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api-mp
            Method: post
        XeexExcQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api-mp
            Method: get
  XeexExcMaintainanceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/XeexExcMaintainance
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        XeexExcInsert:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api-main
            Method: post
        XeexExcQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xeex-api-main
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  XeexExcApi:
    Description:
      'API Gateway endpoint URL for Prod stage for XEEX EX Connect function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/xeex-exc/'
  XeexExcApiFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt XeexExcApiFunction.Arn
  XeexExcApiFunctionIamRole:
    Description: 'Implicit IAM Role created for XEEX EX Connect function'
    Value: !GetAtt XeexExcApiFunctionRole.Arn
